version: '3'
services:
  web:
    volumes:
      - ./app:/app
    ports:
      - "5000:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - FLASK_APP=/app/ubqc
      - 'RUN=bash -c "bash /app/prestart.sh && flask run --host=0.0.0.0 --port=80"'
    command: bash -c "bash /app/prestart.sh && flask run --host=0.0.0.0 --port=80"
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
